In [25]:
import time            
import re            
import os    
import sys  
import codecs  
import shutil  
import numpy as np  
import matplotlib  
import scipy  
import pandas as pd
import matplotlib.pyplot as plt  
from sklearn import feature_extraction    
from sklearn.feature_extraction.text import TfidfTransformer    
from sklearn.feature_extraction.text import CountVectorizer  
from sklearn.feature_extraction.text import HashingVectorizer

In [26]:
#一个群集
cluster = open('../testE.txt',encoding='utf-8').read().split('\n')
cluster[0]

# len(review)

"  play\t toy\t love\t make\t son\t 's\t like\t littl\t veri\t time\t gift\t recommend\t realli\t bought\t just\t look\t n't\t price\t kid\t good\t old\t christma\t qualiti\t daughter\t fun\t happi\t bit\t great\t year\t use"

In [27]:
#quality
qual_word = open('./dic/attri/quality.txt').read().split('\t')
qual_word = set(qual_word)
len(qual_word)

78

In [28]:
#portable
portable_word = open('./dic/attri/portable.txt').read().split('\t')
portable_word =set(portable_word)
len(portable_word)

49

In [29]:
#brand
brand_word = open('./dic/attri/brand.txt').read().split('\t')
brand_word =set(brand_word)
len(brand_word)

19

In [30]:
#price
price_word = open('./dic/attri/price.txt').read().split('\t')
price_word = set(price_word)
len(price_word)

22

In [31]:
#innovative
inno_word = open('./dic/attri/innovative.txt').read().split('\t')
inno_word = set(inno_word)
len(inno_word)

17

In [32]:
#web
web_word = open('./dic/attri/web.txt').read().split('\t')
web_word = set(web_word)
len(web_word)

27

In [34]:
score = []
Score =[]
T=[]
Term = []

i= 0
for c in cluster:
    quality = 0
    portable = 0
    brand = 0
    price = 0
    innovative = 0
    web = 0
    term = c.split('\t ')
    
    
    Q=[]
    P=[]
    B=[]
    Pr=[]
    I=[]
    W=[]
    
    for t in term:
        if t in qual_word:
            quality +=1
            Q.append(t)
        elif t in portable_word:
            portable +=1
            P.append(t)
    
        elif t in brand_word:
            brand +=1
            B.append(t)
        elif t in price_word:
            price +=1
            Pr.append(t)
        elif t in inno_word:
            innovative += 1
            I.append(t)
        elif t in web_word:
            web +=1
            W.append(t)
        score = ([quality,portable,brand,price,innovative,web])
        T=([Q,P,B,Pr,I,W])
#         print(T)
    Score.append(score)
    Term.append(T)
#     print(Term)
    ATerm = np.array(Term)
# print(Score)
Ascore = np.array(Score)
print('++++++++++++++++++++++++++++++++')
print(Ascore)
ATerm

++++++++++++++++++++++++++++++++
[[1 1 0 1 0 1]
 [1 1 0 1 0 1]
 [1 1 0 1 0 1]
 [1 1 0 0 0 1]
 [1 1 0 1 0 1]
 [1 1 0 1 0 0]
 [1 1 0 1 0 1]
 [1 1 0 1 0 1]
 [1 1 0 1 0 1]
 [1 1 0 1 0 1]]


array([[list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list([]), list([]),
        list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list([])],
       [list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list(['price']),
        list([]), list(['happi'])],
       [list(['qualiti']), list(['time']), list([]), list(['

In [35]:
ATerm.shape

(10, 6)

In [36]:
Ascore.shape

(10, 6)

In [37]:
Frame = pd.DataFrame(Ascore,columns=['質量','可攜性','品牌','價格','創新性','網站內容'])

In [38]:
Frame[:10]

質量  可攜性  品牌  價格  創新性  網站內容
0   1    1   0   1    0     1
1   1    1   0   1    0     1
2   1    1   0   1    0     1
3   1    1   0   0    0     1
4   1    1   0   1    0     1
5   1    1   0   1    0     0
6   1    1   0   1    0     1
7   1    1   0   1    0     1
8   1    1   0   1    0     1
9   1    1   0   1    0     1

In [22]:
Frame.to_csv('../test_score.csv')

In [39]:
TATerm = ATerm.reshape(6,10)

In [40]:
TATerm.shape

(6, 10)

In [41]:
AFrame = pd.DataFrame(ATerm,columns=['質量','可攜性','品牌','價格','創新性','網站內容'])

In [42]:
AFrame

質量     可攜性  品牌       價格 創新性     網站內容
0  [qualiti]  [time]  []  [price]  []  [happi]
1  [qualiti]  [time]  []  [price]  []  [happi]
2  [qualiti]  [time]  []  [price]  []  [happi]
3  [qualiti]  [time]  []       []  []  [happi]
4  [qualiti]  [time]  []  [price]  []  [happi]
5  [qualiti]  [time]  []  [price]  []       []
6  [qualiti]  [time]  []  [price]  []  [happi]
7  [qualiti]  [time]  []  [price]  []  [happi]
8  [qualiti]  [time]  []  [price]  []  [happi]
9  [qualiti]  [time]  []  [price]  []  [happi]

In [43]:
AFrame2 = AFrame.T

In [44]:
AFrame2

0          1          2          3          4          5  \
質量    [qualiti]  [qualiti]  [qualiti]  [qualiti]  [qualiti]  [qualiti]   
可攜性      [time]     [time]     [time]     [time]     [time]     [time]   
品牌           []         []         []         []         []         []   
價格      [price]    [price]    [price]         []    [price]    [price]   
創新性          []         []         []         []         []         []   
網站內容    [happi]    [happi]    [happi]    [happi]    [happi]         []   

              6          7          8          9  
質量    [qualiti]  [qualiti]  [qualiti]  [qualiti]  
可攜性      [time]     [time]     [time]     [time]  
品牌           []         []         []         []  
價格      [price]    [price]    [price]    [price]  
創新性          []         []         []         []  
網站內容    [happi]    [happi]    [happi]    [happi]

In [36]:
AFrame2.to_csv('../test_score.csv')